#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: root
#    url: jdbc:mysql://localhost:3306/1905?useUnicode=true&characterEncoding=utf-8
#    username: root
#  data:
#    solr:
#      host: http://127.0.0.1:8080/solr
#    thymeleaf:
#      cache: false
#      mode: LEGACYHTML5
#      prefix: classpath:/templates/
#      suffix: .html
#mybatis:
#  config-locations: classpath:mapping/confg.xml
#  mapper-locations: classpath:mapping/mapper/*.xml
#  type-aliases-package: com.jk.model
#server:
#  port: 8081
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
server:
  port: 8081
